name             'web_app'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures web_app'
long_description 'Installs/Configures web_app'
version          '0.2.11'

depends 'apache2', '~> 3.0.1'
depends 'selinux', '~> 0.9.0'
depends 'mysql2_chef_gem', '~> 1.0.1'
depends 'mysql', '~> 6.0.17'
depends 'database', '~> 4.0.3'
